[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "django-cors-headers>=4.9.0",
    "djangorestframework>=3.18.1",
    "djangorestframework-simplejwt>=5.5.1",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
]
